spring.application.name=user-service
server.port=8081
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.datasource.url=jdbc:postgresql://localhost:5432/vet_user_db
spring.datasource.username=postgres
spring.datasource.password=postgres22
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/vet

keycloak.url=http://localhost:8080
keycloak.realm=vet
keycloak.client-id=admin-cli
keycloak.username=admin
keycloak.password=Admin1@2
keycloak.custom-client-name=vetpath